### ISSUE TITLE
Closing "Window" and title collision?

### ISSUE THREAD

**Issue by Chillance** [golang-ui/nuklear#10]
Hey,

So, this is might not be this libary's problem, although, it might need some additional functions to expose more things, such as a func (p *Panel) IsClosed().

But the owner of the other repo doesn't seem all that active, so I thought I post here too as you are more active and could possible help me out.

So, what say you about this: https://github.com/vurtun/nuklear/issues/361 ?

Thanks!

**Comment by xlab** [comment]
Hi, no quick answer on this from me, I'm quite busy too, also don't know Nuklear so deep as you in the referenced issue. I hope vurtun or dumblob will help sooner :)

**Comment by Chillance** [comment]
Thanks for quick answer. After looking into it a bit more, it seems that this:
if nk.NkGroupBegin(ctx, s(n.Name), nk.WindowMovable|nk.WindowClosable|nk.WindowNoScrollbar|nk.WindowBorder|nk.WindowTitle) != 0 {...}

should actually make it so I don't enter when closing the "node" (panel), but instead I get:
nuklear.h:17834: nk_panel_layout: Assertion `!(layout->flags & NK_WINDOW_HIDDEN)' failed.

I'm just not sure exactly how this is suppose to work and be handled...

**Comment by xlab** [comment]
Unrelated: you can omit `s()` helper with the lates version of Nk, strings there are safe as for  now.

**Comment by Chillance** [comment]
Ah. Cool.

Basically, this is about being able to deal with closed panels, and not windows. So, if you have suggestions here, please do share.

Thanks!

**Comment by xlab** [comment]
Maximum I can do here is to bump the header version :)

**Comment by Chillance** [comment]
Hmm, isn't there a way to link the nuklear.h file so it's taken from the other repo when updating this repo? Although, not as "stable" then I suppose.

**Comment by xlab** [comment]
1) not stable
2) not go-gettable

**Comment by Chillance** [comment]
Yeah, makes sense.
