### ISSUE TITLE
prefix & docs

### ISSUE THREAD

**Issue by jfcg** [golang-ui/nuklear#21]
Hi again,
- Many functions keep their redundant Nk prefix (like NkBegin). Using nk.Begin() in Go looks better instead of nk.NkBegin ;)
- nuklear.h documentation could be copied to Go bindings, since that library is very well documented.

**Comment by xlab** [comment]
Nk prefix let only for function calls, to avoid collision with types which are named the same in many cases.

Documentation cannot be copied as comments are not being analyzed, instead we have a reference to original line in header, so the documentation can be reached in 2 hops.
