### ISSUE TITLE
Update to 2.0.0

### ISSUE THREAD

**Issue by Kernle32DLL** [golang-ui/nuklear#26]
Hi,

Seems like I'm responsible for the recent 2.0.0 version bump in Nuklear (https://github.com/vurtun/nuklear/issues/517) :|

So, when would an update of the bindings to 2.0.0 feasible? The problem is that 2.0.0 introduces breaking API changes.

I could cook up a PR for the required changes if wanted. But I don't see any way to gracefully handle the breaking API change.

**Comment by xlab** [comment]
Thanks! This project isn't managing versions, so let's stick to the latest bug-free.

**Comment by Kernle32DLL** [comment]
Nice, thanks for the quick merge!
