### ISSUE TITLE
Nk and Nk-Example both give errors: undefined Context and Input

### ISSUE THREAD

**Issue by coreyog** [golang-ui/nuklear#34]
The following commands all provide the same error output:

- `go get github.com/golang-ui/nuklear/nk`
- `go get github.com/golang-ui/nuklear/cmd/nk-example`
- `go get -tags opengl2 github.com/golang-ui/nuklear/nk`

Output:
```
# github.com/golang-ui/nuklear/nk
nk/etc.go:9: undefined: Context
nk/etc.go:9: undefined: Input
```

Go 1.9.2 x64
Linux Mint 18.3 x64

I'm sure I've missed something. I know I've got opengl installed properly, I've been toying with go-gl for other stuff and had it building and running properly. I'm not sure what else there is to forget.

**Comment by xlab** [comment]
Both `Context` and `Input` are declared in `nk/types.go`, this is strange.

**Comment by coreyog** [comment]
I don't know how but that file was missing. I deleted all of src/github.com/golang-ui and re-ran go get and it worked. I've never run across go get dropping files but oh well.
