### ISSUE TITLE
Unimplemented: 64-bit mode not compiled in

### ISSUE THREAD

**Issue by ryankshah** [golang-ui/nuklear#35]
Hey guys!

**Initial spec:**
- Running Windows 10
- Have MinGW installed
- Have Go installed

So I've got MinGW and Go as checked versions here:

> gcc -v
> Using built-in specs.
> COLLECT_GCC=gcc
> COLLECT_LTO_WRAPPER=c:/mingw/bin/../libexec/gcc/mingw32/6.3.0/lto-wrapper.exe
> Target: mingw32
> Configured with: ../src/gcc-6.3.0/configure --build=x86_64-pc-linux-gnu --host=mingw32 --target=mingw32 --with-gmp=/mingw --with-mpfr --with-mpc=/mingw --with-isl=/mingw --prefix=/mingw --disable-win32-registry --with-arch=i586 --with-tune=generic --enable-languages=c,c++,objc,obj-c++,fortran,ada --with-pkgversion='MinGW.org GCC-6.3.0-1' --enable-static --enable-shared --enable-threads --with-dwarf2 --disable-sjlj-exceptions --enable-version-specific-runtime-libs --with-libiconv-prefix=/mingw --with-libintl-prefix=/mingw --enable-libstdcxx-debug --enable-libgomp --disable-libvtv --enable-nls
> Thread model: win32
> gcc version 6.3.0 (MinGW.org GCC-6.3.0-1)
> 
> go version
> go version go1.9.2 windows/amd64

However, when I run the `go install github.com/golang-ui/nuklear/nk` or even using `go get` it throws this error:

> 
> go install github.com/golang-ui/nuklear/nk
> # github.com/go-gl/glfw/v3.2/glfw
> cc1.exe: sorry, unimplemented: 64-bit mode not compiled in
> # github.com/go-gl/gl/v3.2-core/gl
> cc1.exe: sorry, unimplemented: 64-bit mode not compiled in
> 
> go get github.com/golang-ui/nuklear/nk
> # github.com/go-gl/glfw/v3.2/glfw
> cc1.exe: sorry, unimplemented: 64-bit mode not compiled in
> # github.com/go-gl/gl/v3.2-core/gl
> cc1.exe: sorry, unimplemented: 64-bit mode not compiled in

How can I resolve this issue?

**Comment by xlab** [comment]
Hi @ryankshah , this is a common issue, you're using a 32-bit MinGW setup. Try to use MSYS2 and install MinGW-w64
http://www.msys2.org

Similar issue with examples of correct `gcc -v` output.
