### ISSUE TITLE
Building with "go build"

### ISSUE THREAD

**Issue by Chillance** [golang-ui/nuklear#4]
So, if I want to build this (in Linux), how exactly should I make things work if I get this:

./main.go:48: undefined: nk.NkGLFW3Init
./main.go:48: undefined: nk.GLFW3InstallCallbacks
./main.go:51: undefined: nk.NkGLFW3FontStashBegin
./main.go:53: undefined: nk.NkGLFW3FontStashEnd
./main.go:72: undefined: nk.NkGLFW3Shutdown
./main.go:89: undefined: nk.NkGLFW3NewFrame
./main.go:138: undefined: nk.NkGLFW3Render

when running "go build" from the nk-example folder. Or, if I structure things "the Go way" in src folder.

$ go get github.com/golang-ui/nuklear/cmd/nk-example
$ nk-example

works fine. But I'm trying to set things up so I can build "the normal way", but I get the above annoyance. I do have the nk.go file in $GOPATH/src/github.com/golang-ui/nuklear/nk/ folder, and the nk.a file, but it's not found anyway for some reason... What am I missing here?

**Comment by xlab** [comment]
Hi @Chillance, sorry for inconvenience but yesterday I renamed the API methods because of new platforms added (not only GLFW). Has to do it.

```
nk.NkGLFW3Init -> nk.NkPlatformInit 
nk.GLFW3InstallCallbacks -> nk.PlatformInstallCallbacks
nk.NkGLFW3FontStashBegin -> nk.NkFontStashBegin 
nk.NkGLFW3FontStashEnd -> nk.NkFontStashEnd
nk.NkGLFW3Shutdown -> nk.NkPlatformShutdown
nk.NkGLFW3NewFrame -> nk.NkPlatformNewFrame
nk.NkGLFW3Render -> nk.NkPlatformRender
```

Current main.go from `master` from nk-example references all things right:
https://github.com/golang-ui/nuklear/blob/master/cmd/nk-example/main.go

**Comment by Chillance** [comment]
Oh, ok. I did a pull, and now it all works. Thanks!
