### ISSUE TITLE
nk_stroke_line not available

### ISSUE THREAD

**Issue by Chillance** [golang-ui/nuklear#5]
Hey!

Seems this nk_stroke_line isn't available in the Go API (nk_draw_list_stroke_line is though). I assume the nk.yml needs to be updated to include it as well?

There is a bunch of others missing too, such as:
nk_stroke_curve
nk_stroke_rect
...

Thanks!

**Comment by xlab** [comment]
Thank for the report @Chillance !
There was a typo in my manifest so these functions were left out. Fixed now, pls check.

**Comment by Chillance** [comment]
Seems to work now, thanks!
