### ISSUE TITLE
What is etc file and what kind of needs is used for ?

### ISSUE THREAD

**Issue by r3mb00** [golang-ui/nuklear#56]
Hi, @xlab.

Unfortunately I did find this from the project documentation either from posted issues.

Can anyone tell for the nob like me, please?

**Comment by xlab** [comment]
We put any helpers that improve usability of Nuklear in that file. For example, many Nuklear configuration options should be set as a private fields of an inner C struct, e.g. https://github.com/golang-ui/nuklear/pull/54 or some state can only be accessed using inner fields of C struct https://github.com/golang-ui/nuklear/pull/47

So `etc.go` contains manually written setters and getters. Hopefully this explains well :)
