### ISSUE TITLE
How to fix [all] Error 127 ?

### ISSUE THREAD

**Issue by r3mb00** [golang-ui/nuklear#57]
Hi, @xlab 

I did:
- go get github.com/xlab/android-go/cmd/android-project
- cd GoMobile/src/github.com/xlab/android-go/cmd/android-project
- make

And got:

go-bindata -pkg main templates/
make: go-bindata: Command not found
Makefile:2: recipe for target 'all' failed
make: *** [all] Error 127

![screenshot at 2018-06-21 09-44-22](https://user-images.githubusercontent.com/9653037/41714610-df7700b2-751e-11e8-999d-488f98c02360.png)

Please, HELP!!

**Comment by xlab** [comment]
Install go-bindata
https://github.com/jteeuwen/go-bindata
`go get github.com/jteeuwen/go-bindata`

But this utility `android-project` is deprecated and should not be used, and make there is for developers only.

**Comment by r3mb00** [comment]
@xlab the only one reason why I post bugs here is to run your golang examples for android on my linux machine but I can't do that how hard I try :(

 android-project shouldn't be used for nobs like me, make is for developers that I really stucked with the issue what should I use to run any of your golang example for android.

Help, please.
