### ISSUE TITLE
is this project dead?

### ISSUE THREAD

**Issue by jcbritobr** [golang-ui/nuklear#63]
I have observed that isn't updated anymore. Is this maintained yet?

**Comment by xlab** [comment]
Hi, you can update to the latest and send a PR.

To do that,
1) Get the latest `nuklear.h` from here: https://raw.githubusercontent.com/vurtun/nuklear/master/nuklear.h

2) Replace the file

3) Run `go get github.com/xlab/c-for-go` and then`make all`

4) Commit the changes with specifying the version, also sync the `CHANGELOG.txt`
