### ISSUE TITLE
how can i use this project in opengl other version, like gl-3.3 or gl 4.1

### ISSUE THREAD

**Issue by alexniver** [golang-ui/nuklear#73]
i have run nuklear success, but i find that nuklear now just support gl 2 and 3.2.
what should i do if i want to use other gl version, for example gl4.1
https://github.com/go-gl/example/blob/master/gl41core-cube/cube.go

**Comment by alexniver** [comment]
find the answer my self , just change nk/impl_glfw_gl3.go  , change 

```
github.com/go-gl/gl/v3.2-core/gl
```
to 
```
github.com/go-gl/gl/v3.3-core/gl
```

does the trick

**Comment by xlab** [comment]
Thanks, I won't update the repo, but this is a good tip for new users.
