### ISSUE TITLE
Win64 unable to install: `undefined: gl.Strs`

### ISSUE THREAD

**Issue by nkev** [golang-ui/nuklear#77]
```BASH
$ go version
go version go1.11.2 windows/amd64
$ go install github.com/golang-ui/nuklear/nk
# github.com/golang-ui/nuklear/nk
..\..\go\src\github.com\golang-ui\nuklear\nk\impl_glfw_gl3.go:229:22: undefined: gl.Strs
```
I have a working `gcc version 5.1.0 (tdm64-1)` on Windows 10 64 bit
`git clone` imports but obviously doesn't install

Does anyone know how to resolve this issue?

**Comment by xlab** [comment]
Try to  `go get -u github.com/go-gl/gl/v3.2-core/gl`

The missing function is here:
https://github.com/go-gl/gl/blob/bf2b1f2f34d7f6a60a99a830f65dcd6afb0c6587/v3.2-core/gl/conversions.go#L82

**Comment by nkev** [comment]
That worked, thank you!
